=== Lazagga/GoldfishWalking/Assets/Data/Json/schemas/fantasy.schema.json
{
    "$schema":  "https://json-schema.org/draft/2020-12/schema",
    "title":  "GoldfishWalking Fantasy",
    "type":  "object",
    "required":  [
                     "schemaVersion",
                     "id",
                     "rarity",
                     "effects"
                 ],
    "properties":  {
                       "schemaVersion":  {
                                             "const":  1
                                         },
                       "id":  {
                                  "type":  "string",
                                  "pattern":  "^[A-Za-z0-9_.-]+$"
                              },
                       "designerName":  {
                                            "type":  "string"
                                        },
                       "designerNote":  {
                                            "type":  "string"
                                        },
                       "enabled":  {
                                       "type":  "boolean"
                                   },
                       "sourceId":  {
                                        "type":  "integer"
                                    },
                       "localization":  {
                                            "type":  "object"
                                        },
                       "presentation":  {
                                            "type":  "object"
                                        },
                       "rarity":  {
                                      "enum":  [
                                                   "white",
                                                   "blue",
                                                   "red"
                                               ]
                                  },
                       "tags":  {
                                    "type":  "array",
                                    "items":  {
                                                  "type":  "string"
                                              }
                                },
                       "effects":  {
                                       "type":  "array",
                                       "items":  {
                                                     "type":  "object",
                                                     "required":  [
                                                                      "target",
                                                                      "operation"
                                                                  ]
                                                 }
                                   }
                   },
    "additionalProperties":  false
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_damage_humitcrab.json
{
    "schemaVersion": 1,
    "id": "fan_damage_humitcrab",
    "sourceId": 62,
    "designerName": "소라게",
    "designerNote": "100의 피해를 받을 때마다 체력을 20 얻음",
    "enabled": true,
    "localization": {
        "name": "",
        "description": ""
    },
    "presentation": {
        "sprite": ""
    },
    "rarity": "white",
    "tags": [
        "take_damage"
    ],
    "effects": [
        {
            "trigger": {
                "event": "take_damage"
            },
            "target": {
                "actor": "player",
                "stat": "health"
            },
            "operation": "modify_value",
            "mode": "add",
            "amount": {
                "expression": "floor(IncomingDamageAmount/100)*20"
            }
        }
    ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_end_8ball.json
{
    "schemaVersion":  1,
    "id":  "fan_end_8ball",
    "sourceId":  13,
    "designerName":  "8번 당구공",
    "designerNote":  "내 턴이 끝날 때 모든 상자 속 8의 개수 x40의 피해를 추가로 입힘",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "turn_end"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "turn_end"
                                    },
                        "target":  {
                                       "key":  "damage"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  {
                                       "expression":  "BattleDigit8Count*40"
                                   }
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_turn1_doll.json
{
    "schemaVersion":  1,
    "id":  "fan_turn1_doll",
    "sourceId":  42,
    "designerName":  "대역 인형",
    "designerNote":  "첫 턴동안 적의 힘 -2",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "turn_1"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "turn_1"
                                    },
                        "target":  {
                                       "actor":  "monster",
                                       "stat":  "strength"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  -2.0,
                        "duration":  {
                                         "turns":  1,
                                         "decreaseAt":  "turn_end"
                                     }
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_end_strawberry.json
{
    "schemaVersion":  1,
    "id":  "fan_end_strawberry",
    "sourceId":  24,
    "designerName":  "딸기",
    "designerNote":  "전투 종료 후 체력 +30",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "battle_end"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "battle_end"
                                    },
                        "target":  {
                                       "actor":  "player",
                                       "stat":  "health"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  30.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_acquire_pencil.json
{
    "schemaVersion":  1,
    "id":  "fan_acquire_pencil",
    "sourceId":  12,
    "designerName":  "연필",
    "designerNote":  "소모품을 얻을 때마다, 한 개씩 추가로 얻음",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "acquire_item"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "acquire_item"
                                    },
                        "target":  {
                                       "key":  "item"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  1.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_defend_paperboat.json
{
    "schemaVersion":  1,
    "id":  "fan_defend_paperboat",
    "sourceId":  41,
    "designerName":  "종이 배",
    "designerNote":  "적의 기본 피해량이 내 기본 피해량 이상인 경우, 받는 피해 절반",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "passive"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "take_damage"
                                    },
                        "target":  {
                                       "value":  "incoming_damage"
                                   },
                        "operation":  "modify_value",
                        "mode":  "multiply",
                        "amount":  0.5,
                        "condition":  {
                                          "comparison":  {
                                                             "left":  {
                                                                          "variable":  "monster_base_damage"
                                                                      },
                                                             "operator":  "\u003e=",
                                                             "right":  {
                                                                           "variable":  "player_base_damage"
                                                                       }
                                                         }
                                      },
                        "execution":  "modifier"
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_damage_poinsettia.json
{
    "schemaVersion":  1,
    "id":  "fan_damage_poinsettia",
    "sourceId":  60,
    "designerName":  "포인세티아",
    "designerNote":  "피해를 입을 때 마다 항상 30씩 적게 받음",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "take_damage"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "take_damage"
                                    },
                        "target":  {
                                       "value":  "incoming_damage"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  -30.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_damage_anchor.json
{
    "schemaVersion":  1,
    "id":  "fan_damage_anchor",
    "sourceId":  15,
    "designerName":  "닻",
    "designerNote":  "피해를 입을 때마다 항상 20씩 적게 받음",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "take_damage"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "take_damage"
                                    },
                        "target":  {
                                       "value":  "incoming_damage"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  -20.0
                    }
                ]
}
