=== Lazagga/GoldfishWalking/Assets/Data/Json/schemas/fantasy.schema.json
{
    "$schema":  "https://json-schema.org/draft/2020-12/schema",
    "title":  "GoldfishWalking Fantasy",
    "type":  "object",
    "required":  [
                     "schemaVersion",
                     "id",
                     "rarity",
                     "effects"
                 ],
    "properties":  {
                       "schemaVersion":  {
                                             "const":  1
                                         },
                       "id":  {
                                  "type":  "string",
                                  "pattern":  "^[A-Za-z0-9_.-]+$"
                              },
                       "designerName":  {
                                            "type":  "string"
                                        },
                       "designerNote":  {
                                            "type":  "string"
                                        },
                       "enabled":  {
                                       "type":  "boolean"
                                   },
                       "sourceId":  {
                                        "type":  "integer"
                                    },
                       "localization":  {
                                            "type":  "object"
                                        },
                       "presentation":  {
                                            "type":  "object"
                                        },
                       "rarity":  {
                                      "enum":  [
                                                   "white",
                                                   "blue",
                                                   "red"
                                               ]
                                  },
                       "tags":  {
                                    "type":  "array",
                                    "items":  {
                                                  "type":  "string"
                                              }
                                },
                       "effects":  {
                                       "type":  "array",
                                       "items":  {
                                                     "type":  "object",
                                                     "required":  [
                                                                      "target",
                                                                      "operation"
                                                                  ]
                                                 }
                                   }
                   },
    "additionalProperties":  false
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_acquire_blueprint.json
{
    "schemaVersion":  1,
    "id":  "fan_acquire_blueprint",
    "sourceId":  50,
    "designerName":  "청사진",
    "designerNote":  "획득시 보유하고 있는 환상 중 하나로 선택하여 그 복사본으로 영구히 변경됨",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "on_acquire"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "on_acquire"
                                    },
                        "target":  {
                                       "key":  "fantasy"
                                   },
                        "operation":  "replace_with_copy",
                        "mode":  "replace_with_copy",
                        "amount":  1.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_end_firecracker.json
{
    "schemaVersion":  1,
    "id":  "fan_end_firecracker",
    "sourceId":  46,
    "designerName":  "폭죽",
    "designerNote":  "턴 종료시 이번 전투에서 소모품을 사용한 횟수만큼 30의 피해",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "turn_end"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "turn_end"
                                    },
                        "target":  {
                                       "key":  "damage"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  {
                                       "expression":  "ItemUseCount*30"
                                   }
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_number_applepie.json
{
    "schemaVersion":  1,
    "id":  "fan_number_applepie",
    "sourceId":  56,
    "designerName":  "사과파이",
    "designerNote":  "적의 5보다 큰 숫자가 모두 5로 취급됨",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "passive"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "passive"
                                    },
                        "target":  {
                                       "key":  "monster_number"
                                   },
                        "operation":  "digit_max",
                        "mode":  "digit_max",
                        "amount":  5.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_shop_stampcoupon.json
{
    "schemaVersion":  1,
    "id":  "fan_shop_stampcoupon",
    "sourceId":  39,
    "designerName":  "스탬프쿠폰",
    "designerNote":  "상점에서 체력 999 소모 시 매 턴 공격 횟수 +1의 환상으로 변경",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "blue",
    "tags":  [
                 "shop_purchase"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "shop_purchase"
                                    },
                        "target":  {
                                       "key":  "health_spent"
                                   },
                        "operation":  "transform_value",
                        "mode":  "transform",
                        "amount":  999,
                        "execution":  "capability",
                        "options":  "fan_turn_syringe"
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_turn_pisces.json
{
    "schemaVersion":  1,
    "id":  "fan_turn_pisces",
    "sourceId":  32,
    "designerName":  "물고기자리",
    "designerNote":  "턴 시작 시 이동 횟수가 0이 되는 대신, 그만큼 임시 여분성냥과 지우개 획득",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "red",
    "tags":  [
                 "turn_start"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "turn_start"
                                    },
                        "target":  {
                                       "key":  "extra_match"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  {
                                       "expression":  "RemainingMoves"
                                   },
                        "lifetime":  "battle"
                    },
                    {
                        "trigger":  {
                                        "event":  "turn_start"
                                    },
                        "target":  {
                                       "key":  "eraser"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  {
                                       "expression":  "RemainingMoves"
                                   },
                        "lifetime":  "battle"
                    },
                    {
                        "trigger":  {
                                        "event":  "turn_start"
                                    },
                        "target":  {
                                       "system":  "battle",
                                       "property":  "movement_limit"
                                   },
                        "operation":  "set_value",
                        "mode":  "set",
                        "amount":  0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_damage_slingshot.json
{
    "schemaVersion":  1,
    "id":  "fan_damage_slingshot",
    "sourceId":  19,
    "designerName":  "새총",
    "designerNote":  "피해를 입힐 때 마다 항상 30씩 추가로 입힘",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "deal_damage"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "deal_damage"
                                    },
                        "target":  {
                                       "actor":  "monster"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  30.0
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_start_paperfrog.json
{
    "schemaVersion":  1,
    "id":  "fan_start_paperfrog",
    "sourceId":  22,
    "designerName":  "종이개구리",
    "designerNote":  "첫 턴동안 적의 힘 -1",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "white",
    "tags":  [
                 "battle_start"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "battle_start"
                                    },
                        "target":  {
                                       "actor":  "monster",
                                       "stat":  "strength"
                                   },
                        "operation":  "modify_value",
                        "mode":  "add",
                        "amount":  -1.0,
                        "duration":  {
                                         "turns":  1,
                                         "decreaseAt":  "turn_end"
                                     }
                    }
                ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/fantasies/fan_odd_gemini.json
{
    "schemaVersion":  1,
    "id":  "fan_odd_gemini",
    "sourceId":  37,
    "designerName":  "쌍둥이자리",
    "designerNote":  "내 홀수의 수치 x2, 짝수는 0으로 취급",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "rarity":  "red",
    "tags":  [
                 "passive"
             ],
    "effects":  [
                    {
                        "trigger":  {
                                        "event":  "passive"
                                    },
                        "target":  {
                                       "key":  "player_number"
                                   },
                        "operation":  "modify_value",
                        "mode":  "multiply",
                        "amount":  2.0,
                        "condition":  {
                                          "expression":  "CurrentValueIsOdd"
                                      }
                    },
                    {
                        "trigger":  {
                                        "event":  "passive"
                                    },
                        "target":  {
                                       "key":  "player_number"
                                   },
                        "operation":  "set_value",
                        "mode":  "set",
                        "amount":  0,
                        "condition":  {
                                          "expression":  "CurrentValueIsEven"
                                      }
                    }
                ]
}
