=== Lazagga/GoldfishWalking/Assets/Data/Json/schemas/monster.schema.json
{
    "$schema":  "https://json-schema.org/draft/2020-12/schema",
    "title":  "GoldfishWalking Monster",
    "type":  "object",
    "required":  [
                     "schemaVersion",
                     "id",
                     "stats",
                     "ai"
                 ],
    "properties":  {
                       "schemaVersion":  {
                                             "const":  1
                                         },
                       "id":  {
                                  "type":  "string",
                                  "pattern":  "^[A-Za-z0-9_.-]+$"
                              },
                       "designerName":  {
                                            "type":  "string"
                                        },
                       "designerNote":  {
                                            "type":  "string"
                                        },
                       "enabled":  {
                                       "type":  "boolean"
                                   },
                       "sourceId":  {
                                        "type":  "integer"
                                    },
                       "localization":  {
                                            "type":  "object"
                                        },
                       "presentation":  {
                                            "type":  "object"
                                        },
                       "encounter":  {
                                         "type":  "object"
                                     },
                       "stats":  {
                                     "type":  "object",
                                     "required":  [
                                                      "health",
                                                      "strength"
                                                  ],
                                     "properties":  {
                                                        "health":  {
                                                                       "type":  "integer",
                                                                       "minimum":  1
                                                                   },
                                                        "strength":  {
                                                                         "type":  "integer"
                                                                     }
                                                    }
                                 },
                       "ai":  {
                                  "type":  "object",
                                  "required":  [
                                                   "mode",
                                                   "patterns"
                                               ],
                                  "properties":  {
                                                     "mode":  {
                                                                  "enum":  [
                                                                               "static",
                                                                               "random"
                                                                           ]
                                                              },
                                                     "patterns":  {
                                                                      "type":  "array",
                                                                      "items":  {
                                                                                    "type":  "string"
                                                                                }
                                                                  }
                                                 }
                              },
                       "passives":  {
                                        "type":  "array",
                                        "items":  {
                                                      "type":  "object",
                                                      "required":  [
                                                                       "operation"
                                                                   ]
                                                  }
                                    }
                   },
    "additionalProperties":  false
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_10103_slime.json
{
    "schemaVersion":  1,
    "id":  "Mob_10103_Slime",
    "sourceId":  10103,
    "designerName":  "슬라임",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  1,
                      "grade":  "normal",
                      "difficulty":  "easy"
                  },
    "stats":  {
                  "health":  160,
                  "strength":  0
              },
    "ai":  {
               "mode":  "random",
               "patterns":  [
                                "SlimeSingle",
                                "2_Single"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_30102_jellyfish.json
{
    "schemaVersion":  1,
    "id":  "Mob_30102_Jellyfish",
    "sourceId":  30102,
    "designerName":  "해파리",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite": "Art/Enemies/Mob_30102_Jellyfish"
                     },
    "encounter":  {
                      "act":  3,
                      "grade":  "normal",
                      "difficulty":  "easy"
                  },
    "stats":  {
                  "health":  800,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "JellyfishSingle",
                                "JellyfishSingle",
                                "JellyfishSkill"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_30107_shadow.json
{
    "schemaVersion":  1,
    "id":  "Mob_30107_Shadow",
    "sourceId":  30107,
    "designerName":  "그림자",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  3,
                      "grade":  "normal",
                      "difficulty":  "normal"
                  },
    "stats":  {
                  "health":  1200,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "3_Single",
                                "3_Single",
                                "3_Multi_1"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_30105_golem.json
{
    "schemaVersion":  1,
    "id":  "Mob_30105_Golem",
    "sourceId":  30105,
    "designerName":  "골렘",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  3,
                      "grade":  "normal",
                      "difficulty":  "normal"
                  },
    "stats":  {
                  "health":  1000,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "2_Single"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_10105_frog.json
{
    "schemaVersion":  1,
    "id":  "Mob_10105_Frog",
    "sourceId":  10105,
    "designerName":  "개구리",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  1,
                      "grade":  "normal",
                      "difficulty":  "normal"
                  },
    "stats":  {
                  "health":  250,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "Skip",
                                "Skip",
                                "Skip",
                                "3_Single"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_30202_knight.json
{
    "schemaVersion":  1,
    "id":  "Mob_30202_Knight",
    "sourceId":  30202,
    "designerName":  "기사",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  3,
                      "grade":  "elite",
                      "difficulty":  "normal"
                  },
    "stats":  {
                  "health":  900,
                  "strength":  0
              },
    "ai":  {
               "mode":  "random",
               "patterns":  [
                                "2_Single",
                                "2_Single",
                                "2_Multi_3",
                                "KnightSkill"
                            ]
           },
    "passives":  [
                     {
                         "operation":  "limit_incoming_damage",
                         "maximum":  20,
                         "until":  {
                                       "comparison":  {
                                                          "left":  {
                                                                       "variable":  "monster_damage_taken_this_battle"
                                                                   },
                                                          "operator":  "\u003e=",
                                                          "right":  400
                                                      }
                                   }
                     }
                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_20303_prophet.json
{
    "schemaVersion":  1,
    "id":  "Mob_20303_Prophet",
    "sourceId":  20303,
    "designerName":  "예언자",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  2,
                      "grade":  "boss",
                      "difficulty":  "normal"
                  },
    "stats":  {
                  "health":  1320,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "ProphetSingle",
                                "ProphetMulti",
                                "ProphetSingle",
                                "ProphetExplode"
                            ]
           },
    "passives":  [

                 ]
}

=== Lazagga/GoldfishWalking/Assets/Data/Json/monsters/mob_30103_orb.json
{
    "schemaVersion":  1,
    "id":  "Mob_30103_Orb",
    "sourceId":  30103,
    "designerName":  "구체",
    "designerNote":  "",
    "enabled":  true,
    "localization":  {
                         "name":  "",
                         "description":  ""
                     },
    "presentation":  {
                         "sprite":  ""
                     },
    "encounter":  {
                      "act":  3,
                      "grade":  "normal",
                      "difficulty":  "easy"
                  },
    "stats":  {
                  "health":  850,
                  "strength":  0
              },
    "ai":  {
               "mode":  "static",
               "patterns":  [
                                "2_Multi_1",
                                "2_Multi_2",
                                "2_Multi_3",
                                "OrbSkill"
                            ]
           },
    "passives":  [

                 ]
}
